#!/usr/bin/env python3
import json
from pathlib import Path
R=Path(__file__).resolve().parents[2];e=[]
d=json.loads((R/"v2/gates/development_auditor_candidate_v2.json").read_text())
if d.get("revision")!=2 or d.get("status")!="CANDIDATE":e.append("V2 contract identity")
for n in range(1,19):
 if not any(x.startswith(f"AC-{n:02d} ") for x in d.get("acceptance_criteria",[])):e.append(f"missing AC-{n:02d}")
if d.get("evidence_sufficiency",{}).get("negative_conclusion_from_single_zero_result_forbidden") is not True:e.append("zero-result sufficiency")
if d.get("independent_review",{}).get("blocking_disagreement_forbids_pass") is not True:e.append("blocking disagreement")
if d.get("approval",{}).get("scope_expansion_requires_new_bound_approval") is not True:e.append("approval scope drift")
ev=json.loads((R/"v2/gates/development_auditor_adoption_evidence_v2.json").read_text())
if ev.get("status")!="ACTIVE" or ev.get("subject")!="CB6-DEVELOPMENT-AUDITOR-V2":e.append("V2 adoption")
if ev.get("evidence",{}).get("candidate_gate",{}).get("run_id")!=37405936430:e.append("candidate evidence")
if ev.get("evidence",{}).get("independent_review",{}).get("run_id")!=37406142902:e.append("review evidence")
ie2e=ev.get("evidence",{}).get("incident_e2e_candidate",{})
if ie2e.get("run_id")!=37410918733 or ie2e.get("conclusion")!="success" or ie2e.get("candidate_head")!="599dccca73b6dfe646672c6af0ad8ffffaac24ab":e.append("incident E2E candidate evidence")
iir=ev.get("evidence",{}).get("incident_e2e_independent_review",{})
if iir.get("run_id")!=37411289491 or iir.get("conclusion")!="success" or iir.get("candidate_head")!="871550b34d9e6d080f58a1a18e08cce606d75aae":e.append("incident E2E independent review evidence")
sfe=ev.get("evidence",{}).get("stage_forgetting_e2e_candidate",{})
if sfe.get("run_id")!=37415772275 or sfe.get("conclusion")!="success" or sfe.get("candidate_head")!="10d6ca132dd0787555710e0000a79dfd3778cb4f":e.append("stage forgetting E2E candidate evidence")
sfir=ev.get("evidence",{}).get("stage_forgetting_e2e_independent_review",{})
if sfir.get("run_id")!=37416002831 or sfir.get("conclusion")!="success" or sfir.get("candidate_head")!="72e28c4a6093f43231dee0bf1b94e8bf8f82f641":e.append("stage forgetting E2E independent review evidence")
rge=ev.get("evidence",{}).get("remaining_gaps_e2e_candidate",{})
if rge.get("run_id")!=37416510493 or rge.get("conclusion")!="success" or rge.get("candidate_head")!="80fa4a0ee6f772e4a3c84936f033d564e44ca440":e.append("remaining gaps E2E candidate evidence")
rgir=ev.get("evidence",{}).get("remaining_gaps_e2e_independent_review",{})
if rgir.get("run_id")!=37416698945 or rgir.get("conclusion")!="success" or rgir.get("candidate_head")!="ce30c73b78df0ec77756f54aeff5cdc4eaa458a1":e.append("remaining gaps E2E independent review evidence")
frte=ev.get("evidence",{}).get("final_red_team_e2e_candidate",{})
if frte.get("run_id")!=37417346890 or frte.get("conclusion")!="success" or frte.get("candidate_head")!="4f8b842afe4345f981be5d2f68ac40b2a18d4bb5":e.append("final red team E2E candidate evidence")
frtir=ev.get("evidence",{}).get("final_red_team_e2e_independent_review",{})
if frtir.get("run_id")!=37417570391 or frtir.get("conclusion")!="success" or frtir.get("candidate_head")!="651d42b4ae59c869a7c94fc62787ac859c9c7e3e":e.append("final red team E2E independent review evidence")
cge=ev.get("evidence",{}).get("completion_gaps_e2e_candidate",{})
if cge.get("run_id")!=37420121872 or cge.get("conclusion")!="success" or cge.get("candidate_head")!="469f0508a6971529d2b6c67d93133835dedb29dd":e.append("completion gaps E2E candidate evidence")
cgir=ev.get("evidence",{}).get("completion_gaps_e2e_independent_review",{})
if cgir.get("run_id")!=37420358113 or cgir.get("conclusion")!="success" or cgir.get("candidate_head")!="e0bda277c8e2e973b907d45b27af79f154f18cca":e.append("completion gaps E2E independent review evidence")
finalcov=ev.get("evidence",{}).get("final_e2e_branch_coverage",{})
if finalcov.get("head")!="bed756ecb9aaa9b78250ae8c42389464e1072aff" or finalcov.get("remaining_gaps_candidate",{}).get("run_id")!=37428013041 or finalcov.get("remaining_gaps_candidate",{}).get("conclusion")!="success" or finalcov.get("remaining_gaps_independent_review",{}).get("run_id")!=37428013105 or finalcov.get("remaining_gaps_independent_review",{}).get("conclusion")!="success" or finalcov.get("development_gate",{}).get("run_id")!=37428013002 or finalcov.get("development_gate",{}).get("conclusion")!="success":e.append("final E2E branch coverage evidence")
atomic=ev.get("evidence",{}).get("atomic_coverage_e2e",{})
if atomic.get("head")!="32bc29594d33079fae45a07fc2f812aa1a623ac9" or atomic.get("candidate",{}).get("run_id")!=37432295608 or atomic.get("candidate",{}).get("conclusion")!="success" or atomic.get("independent_review",{}).get("run_id")!=37432295578 or atomic.get("independent_review",{}).get("conclusion")!="success" or atomic.get("development_gate",{}).get("run_id")!=37432295599 or atomic.get("development_gate",{}).get("conclusion")!="success":e.append("atomic coverage E2E evidence")
pc=json.loads((R/"v2/gates/development_auditor_postchange_certification_v2.json").read_text())
if pc.get("status")!="CERTIFIED" or pc.get("subject")!="CB6-DEVELOPMENT-AUDITOR-V2" or pc.get("postchange_head")!="f4c3bb5de2e163dbf60586e86ebfc42fe377dc12":e.append("postchange certification identity")
if pc.get("development_gate")!={"run_id":37433235541,"conclusion":"success","head_sha":"f4c3bb5de2e163dbf60586e86ebfc42fe377dc12"}:e.append("postchange development gate")
if pc.get("atomic_coverage")!={"candidate":{"run_id":37433225181,"conclusion":"success"},"independent_review":{"run_id":37433235609,"conclusion":"success"}}:e.append("postchange atomic coverage")
if pc.get("root_certification",{}).get("status")!="PROVEN" or pc.get("method_freeze",{}).get("result")!="PASS":e.append("postchange governance certification")
reg=json.loads((R/"v2/gates/operational_rule_registry_v19.json").read_text());cov=json.loads((R/"v2/gates/rule_coverage.json").read_text())
rr=[x for x in reg.get("rules",[]) if x.get("id")=="CB6-DEVELOPMENT-AUDITOR-V2"]
if len(rr)!=1 or rr[0].get("status")!="ACTIVE" or rr[0].get("contract")!="v2/gates/development_auditor_candidate_v2.json":e.append("V2 registry activation")
if any(x.get("id")=="CB6-DEVELOPMENT-AUDITOR-V1" for x in reg.get("rules",[])):e.append("V1 still active in v19")
if cov.get("registry")!="v2/gates/operational_rule_registry_v19.json":e.append("coverage registry")
if not any(x.get("rule_id")=="CB6-DEVELOPMENT-AUDITOR-V2" and x.get("coverage_status")=="MACHINE_ENFORCED" for x in cov.get("entries",[])):e.append("V2 coverage")
if any(x.get("rule_id")=="CB6-DEVELOPMENT-AUDITOR-V1" for x in cov.get("entries",[])):e.append("V1 coverage still current")
if e:
 print("CB6 DEVELOPMENT AUDITOR V2 ACTIVE FAIL:");[print(" -",x) for x in e];raise SystemExit(1)
print("CB6 DEVELOPMENT AUDITOR V2 ACTIVE PASS: adopted V2 authority, AC-01..18, semantic evidence, approval scope and machine coverage preserved")
