#!/usr/bin/env python3
from pathlib import Path
import sys
ROOT=Path(sys.argv[1]).resolve() if len(sys.argv)>1 else Path('comaps').resolve()
p=ROOT/'android/app/src/main/java/app/organicmaps/search/SearchFragment.java'
s=p.read_text(encoding='utf-8')

# Voice recognition result: keep the visible CB6 query consistent with the normalized
# query because the recognition result is generated by the app, not typed by the user.
old='mToolbarController.setQuery(values.get(0));'
new='mToolbarController.setQuery(cb6NormalizeSearchQuery(values.get(0)));'
if old in s:
    s=s.replace(old,new,1)
elif new not in s:
    raise SystemExit('CB6 fuzzy: voice result submission anchor missing')

anchor='  private void startCb6VoiceRecognition(@NonNull Intent fallbackIntent)\n'
helper='''  @NonNull
  private static String cb6NormalizeSearchQuery(@NonNull String raw)
  {
    // Normalize width/composition, but preserve ordinary Japanese place wording.
    // Converting every hiragana character to katakana breaks natural queries
    // such as "札幌駅近くの駐車場", so orthographic tolerance is handled by
    // explicit local aliases below instead.
    String q = java.text.Normalizer.normalize(raw, java.text.Normalizer.Form.NFKC).trim();
    q = q.replace("　", " ");
    while (q.contains("  ")) q = q.replace("  ", " ");

    // Local/free Japanese aliases and common ASR variants. Surrounding place
    // wording such as "札幌駅近くの" is intentionally preserved for CoMaps.
    q = q.replace("セイコマ", "セイコーマート");
    q = q.replace("せいこま", "セイコーマート");
    q = q.replace("セーコマ", "セイコーマート");
    q = q.replace("セコマ", "セイコーマート");
    q = q.replace("せこま", "セイコーマート");
    q = q.replace("ファミマ", "ファミリーマート");
    q = q.replace("ふぁみま", "ファミリーマート");
    q = q.replace("ファミリマート", "ファミリーマート");
    q = q.replace("ガソスタ", "ガソリンスタンド");
    q = q.replace("がそすた", "ガソリンスタンド");
    if (!q.contains("セブンイレブン")) q = q.replace("セブン", "セブンイレブン");
    if (!q.contains("セブンイレブン")) q = q.replace("せぶん", "セブンイレブン");
    q = q.replace("ローソンストア", "ローソン");

    // Common category variants produced by Japanese ASR / short typed queries.
    q = q.replace("コンビニエンスストア", "コンビニ");
    q = q.replace("パーキング", "駐車場");
    q = q.replace("駐車スペース", "駐車場");
    q = q.replace("ガソリンスタンド店", "ガソリンスタンド");
    return q;
  }

'''
if 'private static String cb6NormalizeSearchQuery' not in s:
    if anchor not in s: raise SystemExit('CB6 fuzzy: helper anchor missing')
    s=s.replace(anchor,helper+anchor,1)
else:
    start=s.index('  @NonNull\n  private static String cb6NormalizeSearchQuery')
    end=s.index(anchor,start)
    s=s[:start]+helper+s[end:]

# Typed search must use exactly the same normalization as voice search, but must not
# rewrite the text visible in the toolbar. Only the query passed to the stock CoMaps
# SearchEngine is normalized. This preserves normal editing/history UX while giving
# CB6 aliases and NFKC tolerance to both keyboard and voice input.
old_table='''      SearchEngine.INSTANCE.searchInteractive(requireContext(), getQuery(), isCategory(), mLastQueryTimestamp,
                                              true /* isMapAndTable */);'''
new_table='''      SearchEngine.INSTANCE.searchInteractive(requireContext(), cb6NormalizeSearchQuery(getQuery()), isCategory(), mLastQueryTimestamp,
                                              true /* isMapAndTable */);'''
if old_table in s:
    s=s.replace(old_table,new_table,1)
elif new_table not in s:
    raise SystemExit('CB6 fuzzy: tablet typed-search anchor missing')

old_phone='''      if (!SearchEngine.INSTANCE.search(requireContext(), getQuery(), isCategory(), mLastQueryTimestamp,
                                        mLastPosition.valid, mLastPosition.lat, mLastPosition.lon))'''
new_phone='''      if (!SearchEngine.INSTANCE.search(requireContext(), cb6NormalizeSearchQuery(getQuery()), isCategory(), mLastQueryTimestamp,
                                        mLastPosition.valid, mLastPosition.lat, mLastPosition.lon))'''
if old_phone in s:
    s=s.replace(old_phone,new_phone,1)
elif new_phone not in s:
    raise SystemExit('CB6 fuzzy: phone typed-search anchor missing')

# "Show all on map" starts another stock interactive search. Normalize that engine
# query as well, while retaining the user's original text for history and UI.
old_map='''    SearchEngine.INSTANCE.searchInteractive(
        query, isCategory(),'''
new_map='''    SearchEngine.INSTANCE.searchInteractive(
        cb6NormalizeSearchQuery(query), isCategory(),'''
if old_map in s:
    s=s.replace(old_map,new_map,1)
elif new_map not in s:
    raise SystemExit('CB6 fuzzy: show-on-map search anchor missing')

for required in (
    '"セイコマ", "セイコーマート"',
    '"セブン", "セブンイレブン"',
    '"ファミマ", "ファミリーマート"',
    '"ガソスタ", "ガソリンスタンド"',
    '札幌駅近くの駐車場',
    'java.text.Normalizer.Form.NFKC',
    'searchInteractive(requireContext(), cb6NormalizeSearchQuery(getQuery())',
    'search(requireContext(), cb6NormalizeSearchQuery(getQuery())',
    'cb6NormalizeSearchQuery(query), isCategory()'):
    if required not in s: raise SystemExit('CB6 fuzzy invariant missing: '+required)

p.write_text(s,encoding='utf-8')
print('CB6 fuzzy normalization applied to voice + typed + show-on-map searches; stock CoMaps SearchEngine retained')
